### ISSUE TITLE
Fails to compile with Zig `0.16.0`

### ISSUE THREAD

**Issue by bg-thompson** [jedisct1/zig-minisign#19]
The current version of zig-minisign (`170fea1`) fails to compile with the latest release of the zig compiler (`0.16.0`), seemingly due to the version of the `clap` dependency. Note: the `clap` dependency has been recently updated.

```
$ mkdir zig-minisign
$ cd zig-minisign/
$ git clone https://github.com/jedisct1/zig-minisign.git .
$ zig16 version
0.16.0
$ zig16 build -Doptimize=ReleaseSmall
install
└─ install minizign
   └─ compile exe minizign ReleaseSmall native 1 errors
zig-pkg/clap-0.11.0-oBajBxDoAQChQCl4LRM4tyf-VChKLbhYilS806xxzxrQ/clap.zig:1034:51: error: missing struct field: items
                .list => std.ArrayListUnmanaged(T){},
                         ~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by jedisct1** [comment]
`clap` has been updated, thanks!
