### ISSUE TITLE
Fails to compile on Windows with Zig `0.16.0`

### ISSUE THREAD

**Issue by bg-thompson** [jedisct1/zig-minisign#20]
The latest version of the program (`f2faea2`) fails to compile on Windows 11:

```
$ zig16.exe version
0.16.0
$ zig16.exe build run
run
└─ run exe minizign
   └─ compile exe minizign Debug native 1 errors
src\main.zig:149:29: error: root source file struct 'os.windows.kernel32' has no member named 'GetConsoleMode'
        if (windows.kernel32.GetConsoleMode(handle, &original_console_mode) != 0) {
            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```            

Note: While the function `GetConsoleMode()` in `std/os/windows/kernel32.zig` was present in version `0.15.2` of the Zig compiler, the function no longer exists in `kernel32.zig` in the `0.16.0` release of the compiler.

**Comment by jedisct1** [comment]
Indeed, low-level access to the Win32 API has been removed from the Zig standard library.

Minisign should now compile again on Windows, thanks!
